title: "Portfolio"
author: "Christopher Gullberg Brady"
description: "A quick show of my talents"
baseurl: /
url: "www.christophergullbergbrady.com"

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: false          # show article previews on the home page instead of headlines
hide_title: true            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: ""     # see http://shopify.github.io/liquid/filters/date/

# Theme settings
style: default               # choose between "default", "contrast" and "minimal"
dark_theme: true            # enables dark mode

navigation:                  # (optional) site navigation in the header
  - index.html
  - archive.md
  - about.md

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  envelope: "mailto:christopher.gullbergbrady@gmail.com"
  github: "https://github.com/KyaZero"
  linkedin: "https://www.linkedin.com/in/christopher-gullberg-brady-9a3014149/"
  # rss: "/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
